language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 src tests


after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml